language: php

php:
  - 7.1

sudo: required

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules/

addons:
  apt:
    packages:
    - libfreetype6-dev
    - libjpeg62-turbo-dev
    - libpng-dev
    - libjpeg-dev

before_script:
  - cp .env.circle .env
  - touch database/database.sqlite
  - composer self-update
  - composer install --no-interaction
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - php artisan key:generate
  - npm install
  - npm run dev
  - php artisan serve &

script:
  - vendor/bin/phpunit