language: php

php:
  - 7.1

sudo: false

before_script:
  - cp .env.circle .env
  - touch database/database.sqlite
  - curl -L http://git.io/phpenv-installer | sudo -E bash -
  - phpenv config-rm xdebug.ini
  - phpenv install gd
  - composer self-update
  - composer install --no-interaction
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - php artisan key:generate
  - npm install
  - npm run dev
  - php artisan serve &

script:
  - vendor/bin/phpunit